### ISSUE TITLE
Create simplified new child/relationship creation menu for UML Activity Diagram diagram

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-umllight#10]
The new child / relationship creation menu should only contain the following UML concepts (equal to #4):

* [ ] Activity
* [ ] Initial Node
* [ ] Final Node
* [ ] Activity final
* [ ] Decision node
* [ ] Merge node
* [ ] Join node
* [ ] Fork node
* [ ] Opaque Action
* [ ] Comment
* [ ] Control Flow
* [ ] Link
* [ ] Action
* [ ] Call BehaviorAction
* [ ] CallOperation Action
* [ ] AcceptEventAction
* [ ] Pin
* [ ] InputPin
* [ ] OutputPin

**Comment by cdamus** [comment]
@planger If we support pins, should we not also support object flows?  Otherwise, what is the point of pins?

**Comment by cdamus** [comment]
@planger I'm not sure that `AcceptEventAction` really makes sense, as we don't seem to support `Trigger`s otherwise in *UML Light*.

**Comment by planger** [comment]
@cdamus I'm sorry for the delay! I missed your questions on this issue.

> @planger If we support pins, should we not also support object flows? Otherwise, what is the point of pins? And does Pin in the description mean ValuePin? Because Pin is abstract and there isn't mention of ValuePin.

Re Object Flow: Yes, I think we should include object flow, otherwise, as you say, pins don't make sense. I'm believe this has just been an oversight. I'm not sure where the term value pin comes from. I'm not aware of it either. I interpret this as input and output pins as well.

> @planger I'm not sure that AcceptEventAction really makes sense, as we don't seem to support Triggers otherwise in UML Light.

Right, I think we either also include `SendSignalAction` or we drop `AcceptEventAction`. I looked into the election and we had two votes for `AcceptEventAction` (`SendSignalAction` wasn't in the list to be voted for some reason), so I'd go with including `SendSignalAction` too. It is also included in the [OCUP2](https://www.omg.org/ocup-2/coveragemap-found.htm) list that we used as a reference.

Thanks!

**Comment by planger** [comment]
> Thanks, @planger. We'll have to raise an issue to add ObjectFlow to the Activity Diagram that so far is otherwise complete.

Right, thanks for re-opening the tickets.

> But if we have SendSignalAction, then we will have to include Signal in the class modeling. We need to have signals to send. Then also the MessageSort::async_signal for Messages with signal signature in sequence diagrams. I see that OCUP2 does have Signal and Reception in class modeling, which we also excluded. So we would have to fix that, too. And this suggests then further that isActive should be retained on the UML tab of the properties for Class.

Good point, this opens a whole new line of things we'd have to add. @CharlesAtZelig what do you think?

**Comment by planger** [comment]
Ok, so let's fix `ObjectFlow`.

Re `AcceptEventAction`, I've raised the question with the stakeholders. Until we have feedback, let's exclude `AcceptEventAction` which is the simpler change. We can add it back alongside the whole string of "dependencies" once we receive feedback. Thanks!

**Comment by CharlesAtZelig** [comment]
I am (and was) a proponent for an alignment with OCUP2 Foundation content as this gives more credibility and acceptability to this tool (I was thinking of it as a product... ;-). So anything that is done in that direction gets my blessing.
I think the approach in Philip's last message, to get feedback from our stakeholders is a good one to follow and to ensure that they are successful with this tool - they are our first "clients".
