### ISSUE TITLE
Create custom New Papyrus UMLLight project / model wizard

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-umllight#17]
Create a simplified wizard for creating a UMLLight projects and models. This wizard should have as least options as possible and should only allow to create UMLLight diagrams (see #16).

**Comment by planger** [comment]
I agree, I'd remove both, the template and the profile for now. Thanks!

**Comment by cdamus** [comment]
As discussed off-line, a clean implementation of these new wizards that re-uses the Papyrus wizard classes without resorting to reflection hacks to access private details requires new API in Papyrus.  This is tracked in

- [Eclipse bug 540584](https://bugs.eclipse.org/bugs/show_bug.cgi?id=540584)
- [Gerrit patch 131617](https://git.eclipse.org/r/#/c/131617/)
