### ISSUE TITLE
Create simplified UML Use Case diagram type and palette

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-umllight#3]
The UML Use Case diagram shall include the UML concepts listed below. This includes adapting the palette.

* [ ] Package
* [ ] Subject
* [ ] Actor
* [ ] Use Case
* [ ] Comment
* [ ] Association
* [ ] Generalization
* [ ] Include
* [ ] Extend
* [ ] Comment link

**Comment by cdamus** [comment]
As mentioned on #9, if we're going to have the `Extend` relationship in the palette, then so too must we have `ExtensionPoint` because a the `Extend` has to reference at least one point at which the extending use case is inserted.

**Comment by cdamus** [comment]
@planger In the _Papyrus UML_ use case diagram, the **Subject** tool creates a `Component`.  We seem to be excluding components from the _UML Light_ dialect, so I would suggest that this tool should create a `Class` in our context.  Thoughts?

**Comment by planger** [comment]
> @planger In the Papyrus UML use case diagram, the Subject tool creates a Component. We seem to be excluding components from the UML Light dialect, so I would suggest that this tool should create a Class in our context. Thoughts?

@cdamus Yeah, good idea! I think that's fair.

**Comment by cdamus** [comment]
This is fixed with Pull #27.
