### ISSUE TITLE
[Use Case Diagram] Moving use cases inside of subjects duplicates the use cases

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-umllight#30]
Steps to reproduce:
* Create a subject (i.e. a class) in a use case diagram
* Create a use case inside of the subject
![image](https://user-images.githubusercontent.com/588090/47733579-dbf86a00-dc68-11e8-99a0-6ac1e51d7aee.png)
* Move the use case inside of the subject

Expected Result:
Use case is graphically moved

Actual result:
Use case is duplicated
![image](https://user-images.githubusercontent.com/588090/47733630-eb77b300-dc68-11e8-9b54-1e388541f46b.png)

Note that this seems to be actually a Papyrus bug that has nothing to do with UMLLight. I'm just wondering whether we can either fix it easily in Papyrus or use a different element as a subject to work around this issue.

**Comment by cdamus** [comment]
It's just the view of the use case that's duplicated, not the semantics.  So likely a mistake in one of the diagram's edit-policies.

**Comment by cdamus** [comment]
Yup, it's a problem in the `UsecaseToSubjectInUsecaseDiagramDropStrategy` class.  I'll work up a fix in Papyrus.

**Comment by cdamus** [comment]
There's more to this problem besides the duplication.  If you drag a use case from outside of a subject into that subject, then a view of the use case is created within the subject but it also remains outside.

**Comment by cdamus** [comment]
This problem was already reported in the Eclipse bugzilla:  [bug 535696](http://eclip.se/535696).
