### ISSUE TITLE
Create simplified UML State Machine diagram type and palette

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-umllight#6]
The UML State Machine diagram shall include the UML concepts listed below. This includes adapting the palette.

* [ ] State
* [ ] Initial
* [ ] FinalState
* [ ] Choice
* [ ] Junction
* [ ] Comment
* [ ] Transition
* [ ] Link

**Comment by cdamus** [comment]
The palette has a creation tool for `Region`, which it should not.  I expect that is because composite states and multiple regions in state machines are not supported in *UML Light*?

**Comment by tortmayr** [comment]
If composite states are not supported we have to modify the behavior of the <i>CreationTool</i> for <i>States</i>. Currently if a new state is created on top of an existing one they get merged into a composite state
