### ISSUE TITLE
Set default target to released 2018-12

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-umllight#71]
Now, as 2018-12 should be officially released, we should build on this released version.

**Comment by cdamus** [comment]
We have a problem with this that I am having trouble figuring out.  With a target platform based on the 2018-12 Simultaneous Release repo, Tycho's compiler cannot resolve any SWT APIs.  Note that SWT is special as its API is defined entirely in platform-specific fragments, where every one of those fragments defines Java classes that look and feel the same.  This is just like a problem raised by Ed Merks on the cross-project-dev mailing list.

Until we can figure this out, our build will be stuck on 2018-09.

**Comment by cdamus** [comment]
> Until we can figure this out, our build will be stuck on 2018-09.

Okay, as described in PR #75 I did get to the bottom of this and the PR has a working update to the target platform for 2018-12 release.  It drops the 32-bit Windows platform because that is no longer supported by Eclipse Project.
