### ISSUE TITLE
New relationship menu only includes Dependency

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-umllight#72]
The `New Relationship` menu includes only `Dependency` for almost all elements that I select. Only on packages it also includes `PackageImport`. In `UMLLightNewChild.creationmenumodel` however, there are several more elements specified.

**Comment by tortmayr** [comment]
@planger The relationship menu is context sensitive. It only displays the relationships for which the currently selected element can be declared as source

**Comment by planger** [comment]
Oh, you're absolutely right. I forgot about that. Re-tested and works like a charm. UMLLight is so easy to use that I forgot about just trusting the tool :)
