### ISSUE TITLE
Add vector graphics of Papyrus UMLLight logo

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-umllight#77]
Please add the SVG file of the feather to the repository so that we have a vector version of the logo. Thanks!

**Comment by cdamus** [comment]
Note that I only intended this as a placeholder; hopefully someone can hire a graphic designer to design a logo for the project!

**Comment by CharlesAtZelig** [comment]
Interesting… I actually liked it...

Regards / cordialement,
 
Charles Rivet
Senior Product Manager / directeur principal de produits
charles@zeligsoft.com <mailto:charles@zeligsoft.com>
