### ISSUE TITLE
Create simplified new child/relationship creation menu for UML Use Case diagram

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-umllight#9]
The new child / relationship creation menu should only contain the following UML concepts (equal to #3):

* [ ] Package
* [ ] Subject
* [ ] Actor
* [ ] Use Case
* [ ] Comment
* [ ] Association
* [ ] Generalization
* [ ] Include
* [ ] Extend
* [ ] Comment link

**Comment by cdamus** [comment]
We cannot have the `Extend` element without `ExtensionPoint`, as the `Extend` must specify at least one point in the extended use case at which the extending use case is to be inserted.
